#!/usr/bin/python3
import time
import pygame
import subprocess
import requests
import os

def disk():
    with open("SYS/DISK_INFO.TXT", "w") as f:
        f.write("!DISK!0   IcrogenOS   32MB")

def pchar(msg):
    for i in msg:
        print(end=i, flush=True)
        time.sleep(0.01)

def syserr(code):
    pygame.mixer.music.stop()
    print("\033[H\033[2J")
    pchar("      /\n")
    pchar(".    /\n")
    pchar("    /\n")
    pchar("   /\n")
    pchar("   \\\n")
    pchar(".   \\\n")
    pchar("     \\\n")
    pchar("      \\\n")
    pchar("\nFailed to continue work of IcrogenOS\n")
    pchar(f"Error code: {code}\n")
    time.sleep(5)
    exit()

def first_startup():
    print("Installing all programs...")
    time.sleep(20)
    print("Checking...")
    time.sleep(10)
    print("IcrogenOS Successfully installed on your computer.")
    time.sleep(2)
    print("\033[H\033[2J")
    with open("SYS/CHECK.TXT", "w") as fw:
        fw.write("y")
    pygame.mixer.init()
    pygame.mixer.music.load("SYS/icrogen_first_startup_music.mp3")
    pygame.mixer.music.play()
    print("Welcome to IcrogenOS 0.0.7")
    print("Made by Luxidev")
    time.sleep(2)
    print("\033[H\033[2J")
    time.sleep(1)
    print("This menu help you install all for your IcrogenOS!")
    time.sleep(2)
    print("\033[H\033[2J")
    print("1. Let's set new account for you")
    name = input("Enter your new username: ")
    ps = input("Enter your new password: ")
    with open("SYS/USERNAME.TXT", "w") as f:
        f.write(name)
    with open("SYS/PASSWORD.TXT", "w") as f:
        f.write(ps)
    input("Press enter to continue...")
    print("\033[H\033[2J")
    print("Shutting down. After shutting down power on again your computer.")
    pygame.mixer.music.stop()
    pygame.mixer.music.load("SYS/icrogenos_shutdown_sound.mp3")
    pygame.mixer.music.play()
    time.sleep(11)
    print("\033[H\033[2J")
    exit()

def main():
    pygame.mixer.init()
    time.sleep(2)
    print("\033[H\033[2J", end="\r")
    print("IcrogenOS starting")
    print("4MB RAM")
    print("Icrogen Sound Card")
    print("16MB Memory")
    time.sleep(5)
    print("\033[H\033[2J", end="\r")
    if os.path.exists("SYS/CHECK.TXT"):
        pass
    else:
        first_startup()
    print("Welcome to IcrogenOS")
    time.sleep(1)
    usr = input("Enter username: ")
    pss = input("Enter password: ")
    usrc = open("SYS/USERNAME.TXT", "r")
    pssc = open("SYS/PASSWORD.TXT", "r")
    if usrc.read() == usr:
        pass
    else:
        print("Wrong username. Shutting down.")
        exit()
    if pssc.read() == pss:
        pass
    else:
        print("Wrong password. Shutting down.")
        exit()
    time.sleep(2)
    print("\033[H\033[2J", end="\r")
    print("Welcome to IcroShell")
    pygame.mixer.music.load("SYS/icrogenos_startup_sound.mp3")
    pygame.mixer.music.play()
    cv = "0.0.7"
    while True:
        com = input("> ").split()
        if not com:
            pass
        elif com[0] == "help":
            print("help       System Commands")
            print("echo       Output text in console")
            print("cls        Clear Console")
            print("icroplay   Music Player for IcrogenOS")
            print("laf        List All Files")
            print("icrofetch  System Information")
            print("syserr     System Error")
            print("calc       Calculator for IcrogenOS")
            print("log        Update Log")
            print("shutdown   Shutdown OS")
        elif com[0] == "echo":
            print(f"{' '.join(com[1:])}")
        elif com[0] == "cls":
            print("\033[H\033[2J")
        elif com[0] == "icroplay":
            print("\033[H\033[2J", end="\r")
            print("Welcome to IcroPlay")
            print(" - play <sound_filename>")
            print(" - stop")
            print(" - pause")
            print(" - unpause")
            print(" - exit")
            while True:
                cm = input("> ").split()
                if not cm:
                    pass
                elif cm[0] == "play":
                    music = ''.join(cm[1:])
                    pygame.mixer.music.load(music)
                    pygame.mixer.music.play()
                    print(f"Playing the '{music}'")
                elif cm[0] == "stop":
                    pygame.mixer.music.stop()
                    print(f"Stopped the '{music}'")
                elif cm[0] == "pause":
                    pygame.mixer.music.pause()
                    print(f"Paused the '{music}'")
                elif cm[0] == "unpause":
                    pygame.mixer.music.unpause()
                    print(f"Unpaused the '{music}'")
                elif cm[0] == "exit":
                    break
                else:
                    print(f"Unknown command: {''.join(cm)}")
        elif com[0] == "laf":
            subprocess.run(["dir"])
        elif com[0] == "icrofetch":
            print("OS Name: IcrogenOS")
            print("Developer: Luxidev")
            print("Release date: 05.11.2025")
            print("Release date of first version: 01.11.2025")
            print(f"Current version: {cv}")
            print("RAM: 16MB")
            print("Memory: 32MB")
            print(f"Username: {usr}")
            print(f"Password: {pss}")
        elif com[0] == "syserr":
            syserr("SYSERR_TEST")
        elif com[0] == "calc":
            print("Welcome to Calculator 0.1")
            n1 = float(input("Enter first number: "))
            n2 = float(input("Enter second number: "))
            oper = input("Enter operation (+,-,*,/): ")
            if oper == "+":
                print(n1 + n2)
            elif oper == "-":
                print(n1 - n2)
            elif oper == "*":
                print(n1 * n2)
            elif oper == "/":
                print(n1 / n2)
            else:
                print("Invalid option.")
        elif com[0] == "shutdown":
            print("\033[H\033[2J", end="\r")
            print("Shutdown...")
            pygame.mixer.music.load("SYS/icrogenos_shutdown_sound.mp3")
            pygame.mixer.music.play()
            time.sleep(13)
            exit()
        elif com[0] == "log":
            with open("SYS/UPDATE_LOG.TXT", "r") as f:
                print(f.read())
        else:
            print(f"Unknown command: {''.join(com)}")

def recovery():
    print("\033[H\033[2J", end="\r")
    print("IcrogenOS Recovery Mode starting")
    print("1MB RAM")
    print("2MB Memory")
    time.sleep(5)
    print("\033[H\033[2J", end="\r")
    print("1 > Power Off")
    print("2 > Check disks")
    option = input(">> ")
    if option == "1":
        exit()
    elif option == "2":
        with open("SYS/DISK_INFO.TXT", "r") as f:
            print(f.read())
    else:
        print("Invalid option. Shutdown.")

def bm():
    print("\033[H\033[2J")
    print("IcroBoot 0.0.1")
    print(" - IcrogenOS >>> 1")
    print(" - IcrogenOS Recovery Mode >>> 2")
    print(" - Power Off >>> 3\n")
    option = input(">> ")
    if option == "1":
        main()
    elif option == "2":
        recovery()
    elif option == "3":
        exit()
    else:
        print("Invalid option.")

disk()
bm()
first_startup()